name: customized_flavorizr
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  archive: ^3.1.8
  args: ^2.3.0
  checked_yaml: ^2.0.1
  collection: ^1.15.0
  image: ^3.1.0
  io: ^1.0.3
  json_annotation: ^4.4.0
  sprintf: ^6.0.0
  xml: ^6.1.0
  yaml: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable: